// ─── VENDOR THE UI FONTS LOCALLY ──────────────────────────────────────────────
// F1 Coach is a desktop app that has to work with no internet: the game feeds it
// over UDP and the TTS model is bundled, so a race weekend never needs the
// network. index.html used to pull the four UI families from fonts.googleapis.com
// with a render-blocking <link>, which meant an offline (or firewalled) launch
// stalled on the stylesheet until it timed out and then fell back to system-ui —
// the whole app in the wrong typeface. It also told Google about every launch.
//
// This fetches the woff2 files Google serves and writes public/fonts/fonts.css
// with matching @font-face rules, so the app ships its own copy. Output is
// COMMITTED (same as public/tracks/) — the build does not run this. Re-run it
// only to change the family/weight set below:
//
//   node scripts/fetch-fonts.mjs
//
// Only the `latin` subset is kept: the UI is English-only and every extra subset
// is another file in the installer. Google's CSS2 endpoint returns woff2 (and
// variable fonts where the family has them) when asked with a modern browser UA;
// with the default Node UA it serves legacy TTF instead, hence UA below.

import { mkdirSync, writeFileSync, rmSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = resolve(root, "public/fonts");

// Must stay in sync with the families index.html + lib/ui/tokens.js actually use.
const FAMILIES = [
  "Archivo:wght@400;500;600;700;800;900",
  "Saira+Condensed:wght@400;500;600;700",
  "Rajdhani:wght@500;600;700",
  "JetBrains+Mono:wght@400;500;700;800",
];

// A current-Chrome UA, so Google serves woff2 + variable fonts rather than TTF.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

const cssUrl =
  "https://fonts.googleapis.com/css2?" +
  FAMILIES.map((f) => `family=${f}`).join("&") +
  "&display=swap";

// Split the stylesheet into @font-face blocks, keeping only the latin subset.
// Google emits a `/* latin */` comment line before each block it belongs to.
function latinBlocks(css) {
  const out = [];
  const re = /\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
  for (const m of css.matchAll(re)) {
    if (m[1] === "latin") out.push(m[2]);
  }
  return out;
}

const fileName = (url) => url.split("/").pop().split("?")[0];

async function main() {
  console.log(`[fonts] fetching stylesheet for ${FAMILIES.length} families`);
  const res = await fetch(cssUrl, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`Google Fonts CSS ${res.status}`);
  const css = await res.text();

  const blocks = latinBlocks(css);
  if (!blocks.length) throw new Error("no latin @font-face blocks found — did the CSS2 format change?");

  // Start clean so a removed weight doesn't leave an orphan file behind.
  if (existsSync(outDir)) rmSync(outDir, { recursive: true });
  mkdirSync(outDir, { recursive: true });

  const seen = new Map(); // remote url → local filename (families share files)
  const rewritten = [];
  let bytes = 0;

  for (const block of blocks) {
    const urlMatch = block.match(/url\((https:\/\/[^)]+\.woff2)\)/);
    if (!urlMatch) continue;
    const remote = urlMatch[1];

    if (!seen.has(remote)) {
      const name = fileName(remote);
      const bin = await fetch(remote, { headers: { "User-Agent": UA } });
      if (!bin.ok) throw new Error(`${name}: ${bin.status}`);
      const buf = Buffer.from(await bin.arrayBuffer());
      writeFileSync(resolve(outDir, name), buf);
      seen.set(remote, name);
      bytes += buf.length;
      const family = (block.match(/font-family:\s*'([^']+)'/) || [])[1] || "?";
      const weight = (block.match(/font-weight:\s*([^;]+);/) || [])[1] || "?";
      console.log(`[fonts] ${name}  (${family} ${weight.trim()}, ${(buf.length / 1024).toFixed(0)} kB)`);
    }
    // Point the rule at our own origin and drop the unicode-range (we keep only
    // the latin subset, so the browser must not skip the file for other glyphs).
    const decls = block
      .replace(/url\(https:\/\/[^)]+\.woff2\)/, `url(./${seen.get(remote)})`)
      .replace(/\s*unicode-range:[^;]+;/, "")
      .replace(/^@font-face\s*\{/, "")
      .replace(/\}$/, "")
      .split(";")
      .map((d) => d.trim())
      .filter(Boolean)
      .map((d) => `  ${d};`)
      .join("\n");
    rewritten.push(`@font-face {\n${decls}\n}`);
  }

  const header =
    "/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.\n" +
    "   Self-hosted so the app renders correctly with no network. */\n\n";
  writeFileSync(resolve(outDir, "fonts.css"), header + rewritten.join("\n\n") + "\n");

  console.log(`[fonts] wrote ${seen.size} woff2 + fonts.css to public/fonts/ (${(bytes / 1024).toFixed(0)} kB total)`);
}

main().catch((e) => {
  console.error("[fonts] failed:", e.message);
  process.exit(1);
});
